version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta AMQP
      - "15672:15672" # Painel de admin (opcional)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
